spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
  datasource:
    url: "jdbc:mysql://sql:3306/users?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&allowPublicKeyRetrieval=true"
    username: "users"
    password: "pass"
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081